# Neo4j Configurations
neo4j:
  uri: bolt://localhost:7687
  username: neo4j
  password: capstone
  clean_database: clean
  processed_database: processed

# Bitcoin RPC API
rpc:
  ip: 192.168.19.148
  port: 5001
  username: duck
  password: duck2

# Clustering Analysis
dbscan:
  eps: 0.5
  min_points: 7
  time_window: 15
